// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: storage.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoContentStorageService_WriteFile_FullMethodName  = "/tritontube.VideoContentStorageService/WriteFile"
	VideoContentStorageService_WriteFiles_FullMethodName = "/tritontube.VideoContentStorageService/WriteFiles"
	VideoContentStorageService_ReadFile_FullMethodName   = "/tritontube.VideoContentStorageService/ReadFile"
	VideoContentStorageService_ReadFiles_FullMethodName  = "/tritontube.VideoContentStorageService/ReadFiles"
	VideoContentStorageService_SendFiles_FullMethodName  = "/tritontube.VideoContentStorageService/SendFiles"
	VideoContentStorageService_Shutdown_FullMethodName   = "/tritontube.VideoContentStorageService/Shutdown"
)

// VideoContentStorageServiceClient is the client API for VideoContentStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoContentStorageServiceClient interface {
	WriteFile(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	WriteFiles(ctx context.Context, in *BatchWriteRequest, opts ...grpc.CallOption) (*BatchWriteResponse, error)
	ReadFile(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	ReadFiles(ctx context.Context, in *BatchReadRequest, opts ...grpc.CallOption) (*BatchReadResponse, error)
	SendFiles(ctx context.Context, in *BatchSendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type videoContentStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoContentStorageServiceClient(cc grpc.ClientConnInterface) VideoContentStorageServiceClient {
	return &videoContentStorageServiceClient{cc}
}

func (c *videoContentStorageServiceClient) WriteFile(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, VideoContentStorageService_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoContentStorageServiceClient) WriteFiles(ctx context.Context, in *BatchWriteRequest, opts ...grpc.CallOption) (*BatchWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchWriteResponse)
	err := c.cc.Invoke(ctx, VideoContentStorageService_WriteFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoContentStorageServiceClient) ReadFile(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, VideoContentStorageService_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoContentStorageServiceClient) ReadFiles(ctx context.Context, in *BatchReadRequest, opts ...grpc.CallOption) (*BatchReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchReadResponse)
	err := c.cc.Invoke(ctx, VideoContentStorageService_ReadFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoContentStorageServiceClient) SendFiles(ctx context.Context, in *BatchSendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, VideoContentStorageService_SendFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoContentStorageServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, VideoContentStorageService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoContentStorageServiceServer is the server API for VideoContentStorageService service.
// All implementations must embed UnimplementedVideoContentStorageServiceServer
// for forward compatibility.
type VideoContentStorageServiceServer interface {
	WriteFile(context.Context, *WriteRequest) (*WriteResponse, error)
	WriteFiles(context.Context, *BatchWriteRequest) (*BatchWriteResponse, error)
	ReadFile(context.Context, *ReadRequest) (*ReadResponse, error)
	ReadFiles(context.Context, *BatchReadRequest) (*BatchReadResponse, error)
	SendFiles(context.Context, *BatchSendRequest) (*SendResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedVideoContentStorageServiceServer()
}

// UnimplementedVideoContentStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoContentStorageServiceServer struct{}

func (UnimplementedVideoContentStorageServiceServer) WriteFile(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedVideoContentStorageServiceServer) WriteFiles(context.Context, *BatchWriteRequest) (*BatchWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteFiles not implemented")
}
func (UnimplementedVideoContentStorageServiceServer) ReadFile(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedVideoContentStorageServiceServer) ReadFiles(context.Context, *BatchReadRequest) (*BatchReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFiles not implemented")
}
func (UnimplementedVideoContentStorageServiceServer) SendFiles(context.Context, *BatchSendRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendFiles not implemented")
}
func (UnimplementedVideoContentStorageServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedVideoContentStorageServiceServer) mustEmbedUnimplementedVideoContentStorageServiceServer() {
}
func (UnimplementedVideoContentStorageServiceServer) testEmbeddedByValue() {}

// UnsafeVideoContentStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoContentStorageServiceServer will
// result in compilation errors.
type UnsafeVideoContentStorageServiceServer interface {
	mustEmbedUnimplementedVideoContentStorageServiceServer()
}

func RegisterVideoContentStorageServiceServer(s grpc.ServiceRegistrar, srv VideoContentStorageServiceServer) {
	// If the following call pancis, it indicates UnimplementedVideoContentStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoContentStorageService_ServiceDesc, srv)
}

func _VideoContentStorageService_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoContentStorageServiceServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoContentStorageService_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoContentStorageServiceServer).WriteFile(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoContentStorageService_WriteFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoContentStorageServiceServer).WriteFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoContentStorageService_WriteFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoContentStorageServiceServer).WriteFiles(ctx, req.(*BatchWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoContentStorageService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoContentStorageServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoContentStorageService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoContentStorageServiceServer).ReadFile(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoContentStorageService_ReadFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoContentStorageServiceServer).ReadFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoContentStorageService_ReadFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoContentStorageServiceServer).ReadFiles(ctx, req.(*BatchReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoContentStorageService_SendFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoContentStorageServiceServer).SendFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoContentStorageService_SendFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoContentStorageServiceServer).SendFiles(ctx, req.(*BatchSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoContentStorageService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoContentStorageServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoContentStorageService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoContentStorageServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoContentStorageService_ServiceDesc is the grpc.ServiceDesc for VideoContentStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoContentStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tritontube.VideoContentStorageService",
	HandlerType: (*VideoContentStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteFile",
			Handler:    _VideoContentStorageService_WriteFile_Handler,
		},
		{
			MethodName: "WriteFiles",
			Handler:    _VideoContentStorageService_WriteFiles_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _VideoContentStorageService_ReadFile_Handler,
		},
		{
			MethodName: "ReadFiles",
			Handler:    _VideoContentStorageService_ReadFiles_Handler,
		},
		{
			MethodName: "SendFiles",
			Handler:    _VideoContentStorageService_SendFiles_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _VideoContentStorageService_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}
